title: Jitse Windens - E-Portfolio
description: Welcome to my personal blog page! I will share my projects and events during my education on howest here.
theme: minima

author:
  name: Jitse Windens

minima:
  skin: dark
